--------------------------------------------------------
--  DDL for Table tb_fabricante
--------------------------------------------------------

CREATE TABLE xablau.tb_fabricante
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE xablau.tb_fabricante IS 'Registros de fabricantes';
COMMENT ON COLUMN xablau.tb_fabricante.id IS 'Id de identificacão do fabricante';
COMMENT ON COLUMN xablau.tb_fabricante.nome IS 'Nome do fabricante';

--------------------------------------------------------
--  DML for Table tb_fabricante
--------------------------------------------------------

INSERT INTO xablau.tb_fabricante VALUES (1, 'GM - CHEVROLET');
INSERT INTO xablau.tb_fabricante VALUES (2, 'VW - VOLKSWAGEM');
INSERT INTO xablau.tb_fabricante VALUES (3, 'HYUNDAI');
INSERT INTO xablau.tb_fabricante VALUES (4, 'HONDA');
INSERT INTO xablau.tb_fabricante VALUES (5, 'JEEP');
INSERT INTO xablau.tb_fabricante VALUES (6, 'BMW');
INSERT INTO xablau.tb_fabricante VALUES (7, 'MERCEDES-BENZ');