--------------------------------------------------------
--  DDL for Table tb_moldelo
--------------------------------------------------------

CREATE TABLE xablau.tb_modelo
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    categoria VARCHAR(100) NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    id_fabricante INT NOT NULL CONSTRAINT fk_fabricrante_modelo REFERENCES xablau.tb_fabricante(id),
    PRIMARY KEY (id)
);

COMMENT ON TABLE xablau.tb_modelo IS 'Registros de modelos';
COMMENT ON COLUMN xablau.tb_modelo.id IS 'Id de identificacão do modelo';
COMMENT ON COLUMN xablau.tb_modelo.categoria IS 'Categoria do modelo';
COMMENT ON COLUMN xablau.tb_modelo.descricao IS 'Descrição do modelo';
COMMENT ON COLUMN xablau.tb_modelo.id_fabricante IS 'Id de identificacão do fabricante, chave estrangeira para xablau.tb_fabricante';

--------------------------------------------------------
--  DML for Table tb_moldelo
--------------------------------------------------------

INSERT INTO xablau.tb_modelo VALUES(1, 'HATCH_MEDIO', 'Onix', 1);
INSERT INTO xablau.tb_modelo VALUES(2, 'SEDAN_GRANDE', 'Jetta', 2);
INSERT INTO xablau.tb_modelo VALUES(3, 'HATCH_MEDIO', 'i30', 3);
INSERT INTO xablau.tb_modelo VALUES(4, 'SEDAN_GRANDE', 'Honda Civic', 4);
INSERT INTO xablau.tb_modelo VALUES(5, 'SUV', 'Compass', 5);